//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Proba20
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Планир собес.
    /// </summary>
    // *** Start programmer edit section *** (ПланирСобес CustomAttributes)

    // *** End programmer edit section *** (ПланирСобес CustomAttributes)
    [AutoAltered()]
    [Caption("Планир собес")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПланирСобесE", new string[] {
            "ИметьПриСебе as \'Иметь при себе\'",
            "ДатаПланСобес as \'Дата Регистрации\'",
            "Организация as \'Организация\'",
            "Организация.Наименование as \'Наименование\'",
            "РегистАнкеты as \'Регист анкеты\'",
            "РегистАнкеты.ФИОКандидата as \'ФИО\'",
            "РегистАнкеты.ВакантДолжн.Должности as \'должность\'"}, Hidden=new string[] {
            "Организация.Наименование",
            "РегистАнкеты.ФИОКандидата"})]
    [MasterViewDefineAttribute("ПланирСобесE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    [MasterViewDefineAttribute("ПланирСобесE", "РегистАнкеты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОКандидата")]
    [View("ПланирСобесL", new string[] {
            "ИметьПриСебе as \'Иметь при себе\'",
            "ДатаПланСобес as \'Дата Регистрации\'",
            "Организация.Наименование as \'Наименование\'",
            "РегистАнкеты.ФИОКандидата as \'ФИО\'",
            "РегистАнкеты.ВакантДолжн.Должности as \'должность\'"})]
    public class ПланирСобес : ICSSoft.STORMNET.DataObject
    {
        
        private string fИметьПриСебе;
        
        private System.DateTime fДатаПланСобес;
        
        private IIS.Proba20.Организация fОрганизация;
        
        private IIS.Proba20.РегистАнкеты fРегистАнкеты;
        
        // *** Start programmer edit section *** (ПланирСобес CustomMembers)

        // *** End programmer edit section *** (ПланирСобес CustomMembers)

        
        /// <summary>
        /// ДатаПланСобес.
        /// </summary>
        // *** Start programmer edit section *** (ПланирСобес.ДатаПланСобес CustomAttributes)

        // *** End programmer edit section *** (ПланирСобес.ДатаПланСобес CustomAttributes)
        public virtual System.DateTime ДатаПланСобес
        {
            get
            {
                // *** Start programmer edit section *** (ПланирСобес.ДатаПланСобес Get start)

                // *** End programmer edit section *** (ПланирСобес.ДатаПланСобес Get start)
                System.DateTime result = this.fДатаПланСобес;
                // *** Start programmer edit section *** (ПланирСобес.ДатаПланСобес Get end)

                // *** End programmer edit section *** (ПланирСобес.ДатаПланСобес Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланирСобес.ДатаПланСобес Set start)

                // *** End programmer edit section *** (ПланирСобес.ДатаПланСобес Set start)
                this.fДатаПланСобес = value;
                // *** Start programmer edit section *** (ПланирСобес.ДатаПланСобес Set end)

                // *** End programmer edit section *** (ПланирСобес.ДатаПланСобес Set end)
            }
        }
        
        /// <summary>
        /// ИметьПриСебе.
        /// </summary>
        // *** Start programmer edit section *** (ПланирСобес.ИметьПриСебе CustomAttributes)

        // *** End programmer edit section *** (ПланирСобес.ИметьПриСебе CustomAttributes)
        [StrLen(255)]
        public virtual string ИметьПриСебе
        {
            get
            {
                // *** Start programmer edit section *** (ПланирСобес.ИметьПриСебе Get start)

                // *** End programmer edit section *** (ПланирСобес.ИметьПриСебе Get start)
                string result = this.fИметьПриСебе;
                // *** Start programmer edit section *** (ПланирСобес.ИметьПриСебе Get end)

                // *** End programmer edit section *** (ПланирСобес.ИметьПриСебе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланирСобес.ИметьПриСебе Set start)

                // *** End programmer edit section *** (ПланирСобес.ИметьПриСебе Set start)
                this.fИметьПриСебе = value;
                // *** Start programmer edit section *** (ПланирСобес.ИметьПриСебе Set end)

                // *** End programmer edit section *** (ПланирСобес.ИметьПриСебе Set end)
            }
        }
        
        /// <summary>
        /// Планир собес.
        /// </summary>
        // *** Start programmer edit section *** (ПланирСобес.Организация CustomAttributes)

        // *** End programmer edit section *** (ПланирСобес.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Proba20.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ПланирСобес.Организация Get start)

                // *** End programmer edit section *** (ПланирСобес.Организация Get start)
                IIS.Proba20.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ПланирСобес.Организация Get end)

                // *** End programmer edit section *** (ПланирСобес.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланирСобес.Организация Set start)

                // *** End programmer edit section *** (ПланирСобес.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ПланирСобес.Организация Set end)

                // *** End programmer edit section *** (ПланирСобес.Организация Set end)
            }
        }
        
        /// <summary>
        /// Планир собес.
        /// </summary>
        // *** Start programmer edit section *** (ПланирСобес.РегистАнкеты CustomAttributes)

        // *** End programmer edit section *** (ПланирСобес.РегистАнкеты CustomAttributes)
        [PropertyStorage(new string[] {
                "РегистАнкеты"})]
        [NotNull()]
        public virtual IIS.Proba20.РегистАнкеты РегистАнкеты
        {
            get
            {
                // *** Start programmer edit section *** (ПланирСобес.РегистАнкеты Get start)

                // *** End programmer edit section *** (ПланирСобес.РегистАнкеты Get start)
                IIS.Proba20.РегистАнкеты result = this.fРегистАнкеты;
                // *** Start programmer edit section *** (ПланирСобес.РегистАнкеты Get end)

                // *** End programmer edit section *** (ПланирСобес.РегистАнкеты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланирСобес.РегистАнкеты Set start)

                // *** End programmer edit section *** (ПланирСобес.РегистАнкеты Set start)
                this.fРегистАнкеты = value;
                // *** Start programmer edit section *** (ПланирСобес.РегистАнкеты Set end)

                // *** End programmer edit section *** (ПланирСобес.РегистАнкеты Set end)
            }
        }
        
        // *** Start programmer edit section *** (ПланирСобес.Отправить CustomAttributes)

        // *** End programmer edit section *** (ПланирСобес.Отправить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Отправить()
        {
            // *** Start programmer edit section *** (ПланирСобес.Отправить method implementation)

            return;
            // *** End programmer edit section *** (ПланирСобес.Отправить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПланирСобесE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланирСобесE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланирСобесE", typeof(IIS.Proba20.ПланирСобес));
                }
            }
            
            /// <summary>
            /// "ПланирСобесL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланирСобесL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланирСобесL", typeof(IIS.Proba20.ПланирСобес));
                }
            }
        }
    }
}
